<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign In</name>
   <tag></tag>
   <elementGuidId>3b066dbb-9eb6-4566-aa77-ed55d5d912fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MenuContent</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MenuContent']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>890bb68d-a99f-46d7-b97b-412baf0c107a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MenuContent</value>
      <webElementGuid>ef4fd62e-f8d8-4597-9509-124a2f54a254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  
	Sign In
    ?</value>
      <webElementGuid>b38fbbcb-dfc6-4898-904d-ca12d6c014e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MenuContent&quot;)</value>
      <webElementGuid>f97d7b57-f77c-4222-be28-7395c162a3a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='MenuContent']</value>
      <webElementGuid>95d06eff-f21a-430e-8100-83e5e3527921</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Menu']/div</value>
      <webElementGuid>bc9caea6-33ec-4d24-81f5-0ad0224459de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>94bb6da9-50b1-4bf0-a2ff-aa6388eedb47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'MenuContent' and (text() = '  
	Sign In
    ?' or . = '  
	Sign In
    ?')]</value>
      <webElementGuid>010db5fd-fdef-442f-ae5e-c8392bfe5ddd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
