<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>551c0e2e-cba0-4578-a141-3be48dd15708</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(5) > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='QuickLinks']/a[5]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1ade13a4-7674-4184-8df4-c5f8e7fd7adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/sm_birds.gif</value>
      <webElementGuid>b38dc6cf-13b7-46a3-bb90-8d2f130b1f91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QuickLinks&quot;)/a[5]/img[1]</value>
      <webElementGuid>e2f39f81-7f7f-495f-8091-391d41beee71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='QuickLinks']/a[5]/img</value>
      <webElementGuid>04144b1b-44f9-4b7f-b246-1ccd6b3a40d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[5]/img</value>
      <webElementGuid>170b8895-01e5-4da1-aca3-69a64855e48b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/sm_birds.gif']</value>
      <webElementGuid>9b2c2635-cceb-4154-b2d4-e423500d2b93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
