<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>sub_Copyright www.mybatis.org</name>
   <tag></tag>
   <elementGuidId>83b5ccc5-c691-4019-9c34-9e5a6194db85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>sub</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Content']/p[2]/sub</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>sub</value>
      <webElementGuid>de19d1b1-d9ce-4819-87c8-1831a58fb370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copyright www.mybatis.org </value>
      <webElementGuid>54fac813-0812-4095-8ab3-00aba83ecd24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Content&quot;)/p[2]/sub[1]</value>
      <webElementGuid>b02ec8e5-b69f-4fa2-ab89-8fd5471c1ad8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Content']/p[2]/sub</value>
      <webElementGuid>5f20904e-68c1-436f-949f-ba9e0fa97a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter the Store'])[1]/following::sub[1]</value>
      <webElementGuid>091ec2dc-a3b4-4837-aa45-6454610990b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome to JPetStore 6'])[1]/following::sub[1]</value>
      <webElementGuid>67194701-5553-4ca4-a320-9074748a3c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'Content', '&quot;', ')/p[2]/sub[1]')])[1]/preceding::sub[1]</value>
      <webElementGuid>6bef2eb8-13eb-4407-9799-d9ed5b075a86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copyright www.mybatis.org']/parent::*</value>
      <webElementGuid>35636304-9213-4d91-b1d2-83efbab51166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//sub</value>
      <webElementGuid>7642e545-b16c-4c43-a73e-c802d9a36681</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//sub[(text() = 'Copyright www.mybatis.org ' or . = 'Copyright www.mybatis.org ')]</value>
      <webElementGuid>35daa538-c9b8-4876-a1c6-3b776ae0061d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
